index:
  path: /
  controller: App\Controller\Landing::index
  methods: GET

display-table:
  path: /display/table
  controller: App\Controller\Display::table
  methods: GET
display-labels:
  path: /display/labels
  controller: App\Controller\Display::listLabels
  methods: GET
display-create:
  path: /display/create
  controller: App\Controller\DisplayEdit::create
  methods: POST
display-delete:
  path: /display/{id}/delete
  controller: App\Controller\DisplayEdit::delete
  methods: POST
display-save-presentations:
  path: /display/{id}/presentations/save
  controller: App\Controller\DisplayEdit::savePresentations
  methods: POST
display-present:
  path: /display/{id}/present
  controller: App\Controller\Display::present
  methods: GET
# frame-list-by-display:
#   path: /display/{id}/frame/all
#   controller: App\Controller\Frame::listByDisplay
#   methods: GET
carousel-list-by-display:
  path: /display/{id}/carousel/all
  controller: App\Controller\Display::carouselListByDisplay
  methods: GET

carousel-table:
  path: /carousel/table
  controller: App\Controller\Carousel::table
  methods: GET
carousel-create:
  path: /carousel/create
  controller: App\Controller\CarouselEdit::create
  methods: POST
carousel-delete:
  path: /carousel/{id}/delete
  controller: App\Controller\CarouselEdit::delete
  methods: POST
carousel-save-frames:
  path: /carousel/{id}/frames/save
  controller: App\Controller\CarouselEdit::saveFrames
  methods: POST
frame-list-by-carousel:
  path: /carousel/{id}/frame/all
  controller: App\Controller\Frame::listByCarousel
  methods: GET

youtube-video-length:
  path: /youtube/{videoId}/length
  controller: App\Controller\Youtube::length
  methods: GET
google-slides-save:
  path: /google-slides/{presentationId}/save
  controller: App\Controller\GoogleSlides::save
  methods: POST

controller-create:
  path: /remote/create
  controller: App\Controller\RemoteControllerEdit::create
  methods: POST
controller-delete:
  path: /remote/{id}/delete
  controller: App\Controller\RemoteControllerEdit::delete
  methods: POST
controller-table:
  path: /remote/table
  controller: App\Controller\RemoteController::table
  methods: GET
controller-save-buttons:
  path: /remote/{id}/buttons/save
  controller: App\Controller\RemoteControllerEdit::saveButtons
  methods: POST
controller-url:
  path: /remote/{id}
  controller: App\Controller\RemoteController::show
  methods: GET

button-list-by-controller:
  path: /remote/{id}/button/all
  controller: App\Controller\Button::listByController
  methods: GET
button-list-all:
  path: /button/all
  controller: App\Controller\Button::listAll
  methods: GET
button-create:
  path: /button/create/
  controller: App\Controller\ButtonEdit::create
button-edit:
  path: /button/{id}/edit/
  controller: App\Controller\ButtonEdit::edit
button-delete:
  path: /button/{id}/delete/
  controller: App\Controller\ButtonEdit::delete
  methods: POST

template-table:
  path: /template/table
  controller: App\Controller\Template::table
  methods: GET
template-create:
  path: /template/create
  controller: App\Controller\TemplateEdit::create
  methods: POST
template-delete:
  path: /template/{id}/delete
  controller: App\Controller\TemplateEdit::delete
  methods: POST