index:
  path: /
  controller: App\Controller\DefaultController::index
create-display:
  path: /create-display
  controller: App\Controller\DisplayController::create
create-carousel:
  path: /create-carousel
  controller: App\Controller\CarouselController::create
create-controller:
  path: /create-controller
  controller: App\Controller\ControllerController::create